spring.application.name=task-app

server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show.sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

jwt.secret=${JWT_SECRET}


cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.bucket-name=saidonebucket
cloudflare.r2.endpoint=${R2_ENDPOINT}
cloudflare.r2.region=${R2_REGION}